apiVersion: template.openshift.io/v1
kind: Template
labels:
    template: integration-master-pipeline
metadata:
  annotations:
    description: RHTE Deployment Pipeline
  name: integration-master-pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
    name: integration-master-pipeline
    name: integration-master-pipeline
  spec:
    output: null
    postCommit: null
    resources: null
    runPolicy: Serial
    source:
      type: None
    source:
      git:
        uri: ${GIT_REPO}
        ref: ${GIT_BRANCH}
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
        env:
        - name: GIT_BRANCH
          value: ${GIT_BRANCH}
        - name: GIT_REPO
          value: ${GIT_REPO}
        - name: DEPLOY_MODULE 
          value: ${DEPLOY_MODULE}
        - name: CICD_PROJECT 
          value: ${CICD_PROJECT}
        - name: TEST_PROJECT 
          value: ${TEST_PROJECT}
        - name: PROD_PROJECT 
          value: ${PROD_PROJECT}
        - name: MYSQL_USER 
          value: ${MYSQL_USER}
        - name: MYSQL_PWD 
          value: ${MYSQL_PWD}
        - name: IMAGENAMESPACE 
          value: ${IMAGENAMESPACE}
        - name: IMAGEREGISTRY 
          value: ${IMAGEREGISTRY}
parameters:
- name: GIT_REPO
  value: https://github.com/myeung18/3ScaleFuseAMQ.git
  required: true
- name: GIT_BRANCH
  value: master
  required: true
- name: DEPLOY_MODULE 
  value: all
  required: false
- name: CICD_PROJECT 
  value: rh-dev
  required: false
- name: TEST_PROJECT 
  value: rh-test
  required: false
- name: PROD_PROJECT 
  value: rh-prod
  required: false
- name: MYSQL_USER 
  value: dbuser 
  required: false
- name: MYSQL_PWD
  value: password 
  required: false
- name: IMAGEREGISTRY
  value: 172.30.1.1:5000 
  required: true
- name: IMAGENAMESPACE 
  value: rh-dev 
  required: false
