apiVersion: template.openshift.io/v1
kind: Template
labels:
    template: ${MODULE_NAME}-pipeline
metadata:
  annotations:
    description: RHTE Deployment Pipeline
  name: ${MODULE_NAME}-pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
    name: ${MODULE_NAME}-pipeline
    name: ${MODULE_NAME}-pipeline
  spec:
    output: null
    postCommit: null
    resources: null
    runPolicy: Serial
    source:
      type: None
    source:
      git:
        uri: ${GIT_REPO}
        ref: ${GIT_BRANCH}
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: ${MODULE_NAME}/Jenkinsfile
        env:
        - name: GIT_BRANCH
          value: ${GIT_BRANCH}
        - name: GIT_REPO
          value: ${GIT_REPO}
        - name: OPENSHIFT_HOST 
          value: ${OPENSHIFT_HOST}
        - name: OPENSHIFT_TOKEN 
          value: ${OPENSHIFT_TOKEN}
        - name: MODULE_NAME 
          value: ${MODULE_NAME}
        - name: CICD_PROJECT 
          value: ${CICD_PROJECT}
        - name: TEST_PROJECT 
          value: ${TEST_PROJECT}
        - name: PROD_PROJECT 
          value: ${PROD_PROJECT}
        - name: MYSQL_USER 
          value: ${MYSQL_USER}
        - name: MYSQL_PWD 
          value: ${MYSQL_PWD}
        - name: IMAGENAMESPACE 
          value: ${IMAGENAMESPACE}
        - name: IMAGEREGISTRY 
          value: ${IMAGEREGISTRY}
parameters:
- name: GIT_REPO
  value: https://github.com/myeung18/3ScaleFuseAMQ.git
  required: true
- name: GIT_BRANCH
  value: master
  required: true
- name: OPENSHIFT_HOST 
  value: openshift_HOST
  required: false 
- name: OPENSHIFT_TOKEN
  value: openshift_token
  required: false 
- name: MODULE_NAME
  value: maingateway 
  required: true 
- name: CICD_PROJECT 
  value: rh-dev
  required: false
- name: TEST_PROJECT 
  value: rh-test
  required: false
- name: PROD_PROJECT 
  value: rh-prod
  required: false
- name: MYSQL_USER 
  value: root 
  required: false
- name: MYSQL_PWD
  value: password 
  required: false
- name: IMAGEREGISTRY
  value: ----- 
  required: true
- name: IMAGENAMESPACE 
  value: rh-dev 
  required: false
